apiVersion: apps/v1
kind: Deployment
metadata:
  name: work-beat
  namespace: dify
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: work-beat
  template:
    metadata:
      labels:
        app: work-beat
    spec:
      automountServiceAccountToken: false
      restartPolicy: Always
      containers:
        - name: work-beat
          image: langgenius/dify-api:1.9.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: dify-config
          env:
            - name: MODE
              value: "beat"


      