apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: worker
  namespace: dify
  labels:
    app: worker
    app.kubernetes.io/instance: worker
spec:
  serviceName: worker
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: worker
          image: langgenius/dify-api:1.5.1
          ports:
            - containerPort: 5001
              protocol: TCP
          envFrom:
            - configMapRef:
                name: dify-config
          env:
            - name: MODE
              value: "worker"
            - name: SENTRY_DSN
              valueFrom:
                configMapKeyRef:
                  name: dify-config
                  key: API_SENTRY_DSN
            - name: SENTRY_TRACES_SAMPLE_RATE
              valueFrom:
                configMapKeyRef:
                  name: dify-config
                  key: API_SENTRY_TRACES_SAMPLE_RATE
            - name: SENTRY_PROFILES_SAMPLE_RATE
              valueFrom:
                configMapKeyRef:
                  name: dify-config
                  key: API_SENTRY_PROFILES_SAMPLE_RATE
            - name: INNER_API_KEY_FOR_PLUGIN
              valueFrom:
                configMapKeyRef:
                  name: dify-config
                  key: PLUGIN_DIFY_INNER_API_KEY

          volumeMounts:
            - mountPath: /app/api/storage
              name: worker-storage
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      volumes:
        - name: worker-storage
          persistentVolumeClaim:
            claimName: api-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: dify
spec:
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  selector:
    app: worker
  type: ClusterIP
